const day1 = require('./solutions/day1');
const day2 = require('./solutions/day2');
const day3 = require('./solutions/day3');
const day4 = require('./solutions/day4');
const day5 = require('./solutions/day5');
const day6 = require('./solutions/day6');
const day7 = require('./solutions/day7');
const day8 = require('./solutions/day8');
const day9 = require('./solutions/day9');
const day10 = require('./solutions/day10');
const day11 = require('./solutions/day11');
const day12 = require('./solutions/day12');
const day13 = require('./solutions/day13');
const day14 = require('./solutions/day14');

// day1.part1();
// day1.part2();
// day2.part1();
// day2.part2();
// day3.part1();
// day3.part2();
// day4.part1();
// day4.part1();
// day5.part1();
// day6.part1();
// day6.part2();
// day7.part1();
// day8.part1();
// day9.part1();
// day9.part2();
// day10.part1();
// day10.part2();
// day11.part1();
// day12.part1();
// day12.part2();
// day13.part1();
day14.part1();
